export const Evento = {
  // Propiedad
  CREAR_CONTRATO_PROPIEDAD: "CREAR_CONTRATO_PROPIEDAD",
  TERMINAR_CONTRATO_PROPIEDAD: "TERMINAR_CONTRATO_PROPIEDAD",
  REPORTAR_MANTENIMIENTO_PROPIEDAD: "REPORTAR_MANTENIMIENTO_PROPIEDAD",
  FINALIZAR_MANTENIMIENTO_PROPIEDAD: "FINALIZAR_MANTENIMIENTO_PROPIEDAD",
  RESERVAR_PROPIEDAD: "RESERVAR_PROPIEDAD",
  CANCELAR_RESERVA_PROPIEDAD: "CANCELAR_RESERVA_PROPIEDAD",

  // Contrato
  ACTIVAR_CONTRATO: "ACTIVAR_CONTRATO",
  SUSPENDER_CONTRATO: "SUSPENDER_CONTRATO",
  REANUDAR_CONTRATO: "REANUDAR_CONTRATO",
  TERMINAR_CONTRATO: "TERMINAR_CONTRATO",
  RENOVAR_CONTRATO: "RENOVAR_CONTRATO",
  RECHAZAR_CONTRATO: "RECHAZAR_CONTRATO",
   EDITAR: "EDITAR", 

  // Factura
  ENVIAR_FACTURA: "ENVIAR_FACTURA",
  REGISTRAR_PAGO_FACTURA: "REGISTRAR_PAGO_FACTURA",
  MARCAR_VENCIDA_FACTURA: "MARCAR_VENCIDA_FACTURA",
  DISPUTAR_FACTURA: "DISPUTAR_FACTURA",
  AJUSTAR_FACTURA: "AJUSTAR_FACTURA",
  RECHAZAR_DISPUTA_FACTURA: "RECHAZAR_DISPUTA_FACTURA",
  INICIAR_COBRANZA_FACTURA: "INICIAR_COBRANZA_FACTURA",
  DECLARAR_INCOBRABLE_FACTURA: "DECLARAR_INCOBRABLE_FACTURA",

  // Pago
  INICIAR_PROCESAMIENTO_PAGO: "INICIAR_PROCESAMIENTO_PAGO",
  CONFIRMAR_PAGO: "CONFIRMAR_PAGO",
  FALLO_PAGO: "FALLO_PAGO",
  REVERSAR_PAGO: "REVERSAR_PAGO",
  REINTENTAR_PAGO: "REINTENTAR_PAGO",
  CANCELAR_PAGO: "CANCELAR_PAGO",

  // Mantenimiento
  PROGRAMAR_MANTENIMIENTO: "PROGRAMAR_MANTENIMIENTO",
  RECHAZAR_SOLICITUD_MANTENIMIENTO: "RECHAZAR_SOLICITUD_MANTENIMIENTO",
  INICIAR_MANTENIMIENTO: "INICIAR_MANTENIMIENTO",
  CANCELAR_MANTENIMIENTO: "CANCELAR_MANTENIMIENTO",
  FINALIZAR_MANTENIMIENTO: "FINALIZAR_MANTENIMIENTO",
  SUSPENDER_MANTENIMIENTO: "SUSPENDER_MANTENIMIENTO",
  REANUDAR_MANTENIMIENTO: "REANUDAR_MANTENIMIENTO",
  VERIFICAR_MANTENIMIENTO: "VERIFICAR_MANTENIMIENTO",
  REQUERIR_CORRECCIONES_MANTENIMIENTO: "REQUERIR_CORRECCIONES_MANTENIMIENTO",
  REANUDAR_CORRECCIONES_MANTENIMIENTO: "REANUDAR_CORRECCIONES_MANTENIMIENTO",
} as const;
export type Evento = typeof Evento[keyof typeof Evento];

// ============================
// Eventos de usuario
// ============================
export const EventoUsuario = {
  VALIDAR_USUARIO: "VALIDAR_USUARIO",
  REPORTAR_INCUMPLIMIENTO: "REPORTAR_INCUMPLIMIENTO",
  REACTIVAR_USUARIO: "REACTIVAR_USUARIO",
  ELIMINAR_USUARIO: "ELIMINAR_USUARIO",
} as const;
export type EventoUsuario = typeof EventoUsuario[keyof typeof EventoUsuario];